#!/usr/bin/env bash
set -euo pipefail
cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.."
tool/dart format --output=none --set-exit-if-changed lib test integration_test
tool/flutter analyze
tool/flutter test
tool/build_web
